#%RAML 1.0
title: Retail Salesforce Customer System API
version: v2.0
baseUri: https://localhost:8082/api

uses:
  customer: exchange_modules/org.mule.templates/retail-customer-types/1.0.1/retail_customer_types.raml

types:
  Contact:
    type: customer.Customer
    description: Contact information
    properties:
      customerId?: 
        type: string
        description: identifier of customer
      phone?: 
        type: string
        description: phone number
      email?: 
        type: string
        description: email address

/customers:          
  /{customerId}:          
    get:
      displayName: Retrieve customer contact
      description: Return customer information by customerId 
      responses:
        200: 
          body:
            application/json:
              type: Contact
              example: !include examples/get_contact_example.json